"""Add Category model

Revision ID: 623454ed0a9a
Revises: 1818b315bd41
Create Date: 2025-05-14 14:23:19.532108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623454ed0a9a'
down_revision = '1818b315bd41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
