"""Change Product qty to stock

Revision ID: ff9b8de14b8b
Revises: 43f9b6275647
Create Date: 2025-05-14 17:49:53.287022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9b8de14b8b'
down_revision = '43f9b6275647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.drop_column('qty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
